apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker-deployment
spec:
  selector:
    matchLabels:
      app: task-tracker-app
  replicas: 2
  template:
    metadata:
      labels:
        app: task-tracker-app
    spec:
      containers:
      - name: task-tracker-app
        image: sharadhiss/argocd-app:1.1
        ports:
        - containerPort: 8080