---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: pre-sync-webhook-
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: webhook-trigger
        image: curlimages/curl
        args:
        - "/bin/sh"
        - "-c"
        - "curl -v -H 'Authorization: Bearer VQuRqzBWsGlYcFH8Cu5PCpV1B1ju5lbCzaDM2ESQfgB5TGEJhiCyMIrGah3zBjDhAzA8yp4y6jpT62LHvymv5P0lQw02RAQUiTxRIjwQStRel4x1i3mcGHk4ZBUnmiA5' -H 'Content-Type: application/json' -X POST -d '{\"deploymentCommits\":[{\"commit_id\":\"32eca1042d202a04a86961c6405c1b0ca311bb1f\",\"commit_sha\":\"32eca1042d202a04a86961c6405c1b0ca311bb1f\",\"repo_url\":\"https://github.com/DineshKuppan/argocd-resource-hooks-example.git\"}],\"environment\":\"PRODUCTION\",\"result\":\"SUCCESS\",\"start_time\":\"2024-11-24T07:41:01.790Z\"}' 'http://192.168.1.2:4000/api/rest/plugins/webhook/connections/1/deployments'"
      restartPolicy: Never

---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: post-sync-notification-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: webhook-trigger-deployment
        image: curlimages/curl
        args:
        - "/bin/sh"
        - "-c"
        - "curl -v -H 'Authorization: Bearer VQuRqzBWsGlYcFH8Cu5PCpV1B1ju5lbCzaDM2ESQfgB5TGEJhiCyMIrGah3zBjDhAzA8yp4y6jpT62LHvymv5P0lQw02RAQUiTxRIjwQStRel4x1i3mcGHk4ZBUnmiA5' -H 'Content-Type: application/json' -X POST -d '{\"deploymentCommits\":[{\"commit_id\":\"32eca1042d202a04a86961c6405c1b0ca311bb1f\",\"commit_sha\":\"32eca1042d202a04a86961c6405c1b0ca311bb1f\",\"repo_url\":\"https://github.com/DineshKuppan/argocd-resource-hooks-example.git\"}],\"environment\":\"PRODUCTION\",\"result\":\"SUCCESS\",\"start_time\":\"2024-11-24T07:41:01.790Z\"}' 'http://192.168.1.2:4000/api/rest/plugins/webhook/connections/1/deployments'"
      restartPolicy: Never
