---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: pre-sync-webhook-
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: webhook-trigger
        image: curlimages/curl
        command:
        - "/bin/sh"
        - "-c"
        - "curl -v -X POST curl --location 'http://192.168.1.2:4000/api/rest/plugins/webhook/connections/1/deployments' --header 'Authorization: Bearer VQuRqzBWsGlYcFH8Cu5PCpV1B1ju5lbCzaDM2ESQfgB5TGEJhiCyMIrGah3zBjDhAzA8yp4y6jpT62LHvymv5P0lQw02RAQUiTxRIjwQStRel4x1i3mcGHk4ZBUnmiA5' --header 'Content-Type: application/json' --data \"{\"deploymentCommits\": [{\"commit_id\": \"32eca1042d202a04a86961c6405c1b0ca311bb1f\",\"commit_sha\": \"32eca1042d202a04a86961c6405c1b0ca311bb1f\",\"repo_url\": \"https://github.com/DineshKuppan/argocd-resource-hooks-example.git\"}],\"environment\": \"PRODUCTION\",\"result\": \"SUCCESS\", \"start_time\": \"$(date +'%Y-%m-%d %H:%M:%S')\"}\""
      restartPolicy: Never

---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: post-sync-notification-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: webhook-trigger-deployment
        image: curlimages/curl
        command:
        - "/bin/sh"
        - "-c"
        - "curl -v -X POST curl --location 'http://192.168.1.2:4000/api/rest/plugins/webhook/connections/1/deployments' --header 'Authorization: Bearer VQuRqzBWsGlYcFH8Cu5PCpV1B1ju5lbCzaDM2ESQfgB5TGEJhiCyMIrGah3zBjDhAzA8yp4y6jpT62LHvymv5P0lQw02RAQUiTxRIjwQStRel4x1i3mcGHk4ZBUnmiA5' --header 'Content-Type: application/json' --data \"{\"deploymentCommits\": [{\"commit_id\": \"32eca1042d202a04a86961c6405c1b0ca311bb1f\",\"commit_sha\": \"32eca1042d202a04a86961c6405c1b0ca311bb1f\",\"repo_url\": \"https://github.com/DineshKuppan/argocd-resource-hooks-example.git\"}],\"environment\": \"PRODUCTION\",\"result\": \"SUCCESS\", \"start_time\": \"$(date +'%Y-%m-%d %H:%M:%S')\"}\""
      restartPolicy: Never
