---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: pre-sync-webhook-
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: webhook-trigger
        image: curlimages/curl
        command:
        - "curl"
        - "-X"
        - "POST"
        - "--data-urlencode"
        - "payload={\"commit_id\": \"$(git rev-parse HEAD)\", \"repo_url\": \"https://github.com/DineshKuppan/argocd-resource-hooks-example.git\"}"
        - "https://github.com/DineshKuppan/argocd-resource-hooks-example.git"
      restartPolicy: Never

---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: post-sync-notification-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: webhook-trigger-deployment
        image: curlimages/curl
        command:
        - "curl"
        - "-X"
        - "POST"
        - "--data-urlencode"
        - "payload={\"environment\":\"PRODUCTION\",\"result\": \"SUCCESS\", \"commit_id\": \"$(git rev-parse HEAD)\", \"repo_url\": \"https://github.com/DineshKuppan/argocd-resource-hooks-example.git\"}"
        - "https://github.com/DineshKuppan/argocd-resource-hooks-example.git"
      restartPolicy: Never